import { createClient } from '@sanity/client';
import { createGroqBuilder, makeSafeQueryRunner } from 'groqd';
import { apiVersion, projectId, dataset, studioUrl } from '$lib/sanity/api';

// 👇 Import Sanity types, generated by your Sanity project.
import type * as SanityTypes from './sanity.types.ts';

const sanityClient = createClient({
	projectId,
	dataset,
	apiVersion,
	useCdn: process.env.NODE_ENV === 'production', // To always get fresh data in dev mode
	stega: {
		studioUrl,
	},
});

// 👇 Create a type-safe query runner
export const runQuery = makeSafeQueryRunner((query) => sanityClient.fetch(query));

// 👇 Create a type-safe query builder
type SchemaConfig = {
	schemaTypes: SanityTypes.AllSanitySchemaTypes;
	referenceSymbol: typeof SanityTypes.internalGroqTypeReferenceTo;
};
export const q = createGroqBuilder<SchemaConfig>({});
